# Generated by Django 5.1.4 on 2024-12-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
