# Generated by Django 5.1.4 on 2024-12-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nave', '0002_shelfmodel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelfmodel',
            name='position_key',
        ),
    ]
