# Generated by Django 5.1.4 on 2024-12-22 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nave', '0005_alter_inventoryitemmodel_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementinmodel',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nave.warehousemodel'),
        ),
    ]
