# Generated by Django 5.1.4 on 2024-12-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nave', '0006_movementinmodel_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementindistributionmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movementinitemmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
