# Generated by Django 5.1.4 on 2024-12-22 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nave', '0008_movementinmodel_distributed_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movementmodel',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_movements', to='nave.warehousemodel'),
        ),
        migrations.AddField(
            model_name='movementmodel',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_movements', to='nave.warehousemodel'),
        ),
        migrations.AlterField(
            model_name='movementmodel',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('TRANSFER', 'Transferencia')], max_length=10),
        ),
        migrations.CreateModel(
            name='InternalMovementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('destination_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_internal_movements', to='nave.levelmodel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_movements', to='nave.inventoryitemmodel')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_internal_movements', to='nave.levelmodel')),
            ],
        ),
    ]
