# Generated by Django 5.1.4 on 2024-12-23 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nave', '0009_movementmodel_destination_warehouse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalmovementmodel',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='internalmovementmodel',
            name='source_level_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalmovementmodel',
            name='source_shelf_identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='internalmovementmodel',
            name='destination_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_movements', to='nave.levelmodel'),
        ),
        migrations.AlterField(
            model_name='internalmovementmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nave.inventoryitemmodel'),
        ),
        migrations.AlterField(
            model_name='internalmovementmodel',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internalmovementmodel',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='internalmovementmodel',
            name='source_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_movements', to='nave.levelmodel'),
        ),
    ]
